updated github actions file with possible error

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -3,9 +3,9 @@ name: CI Pipeline (DOC1)
 on:
   #Manually trigger workflow runs
   workflow_dispatch:
-  #Trigger the workflow on push from the main branch
+  #Trigger the workflow on push from the master/main branch
   push:
-    branches: [ main]
+    branches: [ main ]
 
 jobs:
   # Build job
@@ -17,5 +17,8 @@ jobs:
     steps:
       # Check-out your repository
       - uses: actions/checkout@v4
+      - name: To Show Error
+        run: echo "Should fail at this point ..." ; exit 1
+      
       - name: Run a one-line script
         run: echo "Continuous Integration"
