updated github actions file with correction

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -18,7 +18,8 @@ jobs:
       # Check-out your repository
       - uses: actions/checkout@v4
       - name: To Show Error
-        run: echo "Should fail at this point ..." ; exit 1
+        run: echo "Should fail at this point ..." || true
+        exit 1
       
       - name: Run a one-line script
         run: echo "Continuous Integration"
