updated github actions file with correction2

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -1,25 +1,20 @@
 name: CI Pipeline (DOC1)
 
 on:
-  #Manually trigger workflow runs
   workflow_dispatch:
-  #Trigger the workflow on push from the master/main branch
   push:
     branches: [ main ]
 
 jobs:
-  # Build job
   build:
     name: My First Pipeline
-    # Run on Ubuntu using the latest version
     runs-on: ubuntu-latest
-    # Job's steps
     steps:
-      # Check-out your repository
       - uses: actions/checkout@v4
-      - name: To Show Error
-        run: echo "Should fail at this point ..." || true
-        exit 1
+      - name: To Show Error (This will fail)
+        run: |
+          echo "Should fail at this point ..."
+          exit 1
       
       - name: Run a one-line script
         run: echo "Continuous Integration"
